# Generated by Django 4.2.30 on 2026-07-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_must_change_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_message_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent chat message', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaignmembership',
            name='role',
            field=models.CharField(choices=[('DM', 'Dungeon Master'), ('PLAYER', 'Player'), ('SPECTATOR', 'Spectator')], max_length=20),
        ),
    ]
