# Generated by Django 4.2.30 on 2026-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_change_user_foreign_keys_to_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_real_name',
            field=models.CharField(blank=True, help_text='Real name at time of posting (preserved after user deletion)', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_username',
            field=models.CharField(blank=True, help_text='Username at time of posting (preserved after user deletion)', max_length=150),
        ),
        migrations.AddField(
            model_name='dicerolllog',
            name='sender_real_name',
            field=models.CharField(blank=True, help_text='Real name at time of rolling (preserved after user deletion)', max_length=100),
        ),
        migrations.AddField(
            model_name='dicerolllog',
            name='sender_username',
            field=models.CharField(blank=True, help_text='Username at time of rolling (preserved after user deletion)', max_length=150),
        ),
    ]
