# Generated by Django 4.2.30 on 2026-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_chatmessage_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('IC', 'In-Character'), ('OOC_RELEVANT', 'Out-of-Character Relevant'), ('OOC_OFFTOPIC', 'Out-of-Character Off Topic'), ('DICE_ROLL', 'Dice Roll')], default='OOC_RELEVANT', max_length=20),
        ),
    ]
