# Generated by Django 4.2.30 on 2026-07-17 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Specific recipients for whisper messages', related_name='received_whispers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='visibility_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('DM_ONLY', 'DM Only - DM and sender only'), ('SECRET_WHISPER', 'Secret Whisper - Selected recipients only (excludes DM)'), ('SPLIT_GROUP', 'Split Group')], default='PUBLIC', max_length=20),
        ),
    ]
