# Generated by Django 6.0.7 on 2026-07-19 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_add_campaign_rule_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_attributes', models.JSONField(blank=True, default=dict, help_text='Attribute overrides/additions for this campaign')),
                ('custom_skills', models.JSONField(blank=True, default=list, help_text='Skill overrides/additions for this campaign')),
                ('rule_book_source', models.CharField(default='custom', help_text="Official rulebook ID or 'custom' for custom content", max_length=100)),
                ('rule_book_title', models.CharField(blank=True, help_text='Title of the selected rule book', max_length=200)),
                ('field_visibility', models.JSONField(blank=True, default=dict, help_text="Visibility rules for fields: 'public', 'player_only', 'dm_only'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to='campaigns.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaignrulebook',
            name='game_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaigngamesettings'),
        ),
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(blank=True, help_text='Character class/archetype', max_length=100)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('background', models.CharField(blank=True, max_length=200)),
                ('attributes', models.JSONField(default=dict, help_text="Attribute values: {'strength': 16, 'dexterity': 14, ...}")),
                ('skills', models.JSONField(default=dict, help_text="Skill values: {'acrobatics': 5, 'stealth': 3, ...}")),
                ('combat_stats', models.JSONField(default=dict, help_text="Combat stats: {'hp': 10, 'max_hp': 10, 'ac': 12, ...}")),
                ('spell_slots', models.JSONField(blank=True, default=dict, help_text="Spell slots by level: {'1': 4, '2': 3, ...}")),
                ('known_spells', models.JSONField(blank=True, default=list, help_text='List of known spells with details')),
                ('prepared_spells', models.JSONField(blank=True, default=list, help_text='Currently prepared spells')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Any additional custom fields')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('description', models.TextField(blank=True)),
                ('field_visibility', models.JSONField(blank=True, default=dict, help_text="Per-field visibility: {'strength': 'public', 'secret_notes': 'dm_only'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('game_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaigngamesettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'campaign', 'name')},
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='character_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.charactersheet'),
        ),
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if created by a user')),
                ('attribute_template', models.JSONField(default=dict, help_text="Predefined attributes (e.g., {'strength': {'label': 'Strength', 'type': 'number', 'default': 10}})")),
                ('skill_template', models.JSONField(default=list, help_text='Predefined skills list')),
                ('combat_stat_template', models.JSONField(default=dict, help_text='Combat stats template (HP, AC, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaigngamesettings',
            name='game_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.gamesystem'),
        ),
    ]
