# Generated by Django 6.0.7 on 2026-07-19 18:27

from django.db import migrations


def populate_default_game_systems(apps, schema_editor):
    """Populate default game systems for character sheets."""
    GameSystem = apps.get_model('campaigns', 'GameSystem')
    
    default_systems = [
        {
            'name': 'Dungeons & Dragons 5e',
            'description': 'Dungeons & Dragons Fifth Edition',
            'is_custom': False,
            'attribute_template': {
                'strength': {'label': 'Strength', 'type': 'number', 'default': 10, 'min': 1, 'max': 30},
                'dexterity': {'label': 'Dexterity', 'type': 'number', 'default': 10, 'min': 1, 'max': 30},
                'constitution': {'label': 'Constitution', 'type': 'number', 'default': 10, 'min': 1, 'max': 30},
                'intelligence': {'label': 'Intelligence', 'type': 'number', 'default': 10, 'min': 1, 'max': 30},
                'wisdom': {'label': 'Wisdom', 'type': 'number', 'default': 10, 'min': 1, 'max': 30},
                'charisma': {'label': 'Charisma', 'type': 'number', 'default': 10, 'min': 1, 'max': 30},
            },
            'skill_template': [
                'acrobatics', 'animal_handling', 'arcana', 'athletics', 'deception',
                'history', 'insight', 'intimidation', 'investigation', 'medicine',
                'nature', 'perception', 'performance', 'persuasion', 'religion',
                'sleight_of_hand', 'stealth', 'survival'
            ],
            'combat_stat_template': {
                'hp': {'label': 'Current HP', 'type': 'number', 'default': 10},
                'max_hp': {'label': 'Max HP', 'type': 'number', 'default': 10},
                'ac': {'label': 'Armor Class', 'type': 'number', 'default': 10},
                'initiative': {'label': 'Initiative', 'type': 'number', 'default': 0},
                'speed': {'label': 'Speed', 'type': 'number', 'default': 30},
                'proficiency_bonus': {'label': 'Proficiency Bonus', 'type': 'number', 'default': 2},
            }
        },
        {
            'name': 'Pathfinder Second Edition',
            'description': 'Pathfinder RPG Second Edition',
            'is_custom': False,
            'attribute_template': {
                'strength': {'label': 'Strength', 'type': 'number', 'default': 10},
                'dexterity': {'label': 'Dexterity', 'type': 'number', 'default': 10},
                'constitution': {'label': 'Constitution', 'type': 'number', 'default': 10},
                'intelligence': {'label': 'Intelligence', 'type': 'number', 'default': 10},
                'wisdom': {'label': 'Wisdom', 'type': 'number', 'default': 10},
                'charisma': {'label': 'Charisma', 'type': 'number', 'default': 10},
            },
            'skill_template': [
                'acrobatics', 'arcana', 'athletics', 'crafting', 'deception', 'diplomacy',
                'intimidation', 'investigation', 'medicine', 'nature', 'occultism',
                'performance', 'religion', 'society', 'stealth', 'survival', 'thievery'
            ],
            'combat_stat_template': {
                'hp': {'label': 'Current HP', 'type': 'number', 'default': 10},
                'max_hp': {'label': 'Max HP', 'type': 'number', 'default': 10},
                'ac': {'label': 'Armor Class', 'type': 'number', 'default': 10},
                'tac': {'label': 'Tactical AC', 'type': 'number', 'default': 10},
                'will_dc': {'label': 'Will DC', 'type': 'number', 'default': 10},
                'reflex_dc': {'label': 'Reflex DC', 'type': 'number', 'default': 10},
                'perception': {'label': 'Perception', 'type': 'number', 'default': 0},
                'speed': {'label': 'Speed', 'type': 'number', 'default': 25},
            }
        },
        {
            'name': 'World of Darkness',
            'description': 'Vampire: The Masquerade / World of Darkness',
            'is_custom': False,
            'attribute_template': {
                'intelligence': {'label': 'Intelligence', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'wits': {'label': 'Wits', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'presence': {'label': 'Presence', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'strength': {'label': 'Strength', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'dexterity': {'label': 'Dexterity', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'stamina': {'label': 'Stamina', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'charisma': {'label': 'Charisma', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'manipulation': {'label': 'Manipulation', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
                'composure': {'label': 'Composure', 'type': 'number', 'default': 1, 'min': 0, 'max': 5},
            },
            'skill_template': [
                'athletics', 'brawl', 'drive', 'firearms', 'larceny', 'stealth', 'survival',
                'awareness', 'empathy', 'expression', 'intimidation', 'leadership', 'performance',
                'science', 'slang', 'streetwise', 'subterfuge'
            ],
            'combat_stat_template': {
                'health': {'label': 'Health Levels', 'type': 'number', 'default': 7},
                'willpower': {'label': 'Willpower', 'type': 'number', 'default': 3},
                'defense': {'label': 'Defense', 'type': 'number', 'default': 0},
                'initiative': {'label': 'Initiative', 'type': 'number', 'default': 0},
            }
        },
    ]
    
    for system_data in default_systems:
        GameSystem.objects.get_or_create(
            name=system_data['name'],
            defaults={
                'description': system_data['description'],
                'is_custom': system_data['is_custom'],
                'attribute_template': system_data['attribute_template'],
                'skill_template': system_data['skill_template'],
                'combat_stat_template': system_data['combat_stat_template'],
            }
        )


def remove_default_game_systems(apps, schema_editor):
    """Remove default game systems on rollback."""
    GameSystem = apps.get_model('campaigns', 'GameSystem')
    for name in ['Dungeons & Dragons 5e', 'Pathfinder Second Edition', 'World of Darkness']:
        GameSystem.objects.filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_add_character_sheet_system'),
    ]

    operations = [
        migrations.RunPython(populate_default_game_systems, remove_default_game_systems),
    ]
