# Generated by Django 6.0.7 on 2026-07-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_populate_default_game_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.character'),
        ),
    ]
