# Generated by Django 6.0.7 on 2026-07-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_make_inventory_character_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='npc_character_id',
            field=models.IntegerField(blank=True, help_text='CharacterSheet ID when DM posts as an NPC', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='npc_character_name',
            field=models.CharField(blank=True, help_text='NPC name at time of posting', max_length=100),
        ),
    ]
